version: '0'

services:
  app:
    image: tomaslobato/sky
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:2222
    volumes:
      - ./:/app
      - ~/sky:/app/sky